name: smart_attendance_scanner
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  mobile_scanner: ^3.5.2         # ✅ QR scanner
  excel: ^2.1.0                  # ✅ Excel export
  intl: ^0.19.0                  # ✅ Date/time formatting
  path_provider: ^2.1.2          # ✅ File system access
  permission_handler: ^11.3.1    # ✅ Storage permission

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/dglogo.png          # ✅ Add your logo to this path
    - assets/IT.xlsx
    - assets/CS.xlsx 